import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "outputs" / "2606.06473"
ANALYSIS = ROOT / "analysis"

PAGES = [
 ("摘要与问题", "MLEvolve 面向长时程机器学习工程，让 LLM 多智能体能够在搜索、执行、反馈中持续进化。", [("三类瓶颈", "现有 MLE Agent 存在分支隔离、无记忆搜索和规划与编码耦合，导致长程优化浪费预算。", "inter-branch information isolation"), ("核心方案", "Progressive MCGS、Retrospective Memory、Adaptive Code Generation 分别对应搜索、经验和控制层。", "self-evolving multi-agent framework"), ("主要结果", "在 12 小时预算下，MLE-Bench 平均奖牌率达到 65.3%，并展示跨到数学优化的泛化能力。", "65.3% average medal rate")]),
 ("引言与框架总览", "论文把长时程 MLE 看成不断提出代码、执行评估、根据反馈改进的开放搜索问题。", [("为什么难", "单次推理只解决一个局部决策，而 MLE 需要在有限时间内连续试错并积累经验。", "long-horizon optimization"), ("图 1 读法", "左侧三类失败模式对应右侧三类组件，最终产物是可提交的 solution.py、submission.csv 和候选解。", "Overview of MLEvolve"), ("设计原则", "搜索结构、记忆系统和代码生成粒度必须共同适应搜索阶段。", "adaptive code generation")]),
 ("贡献与相关工作", "MLEvolve 将既有贪心、MCTS、进化搜索和多智能体工作统一到一个自进化框架中。", [("贡献 1", "用图搜索而非单纯树搜索连接不同分支，使高价值策略可以横向迁移。", "graph-based cross-branch"), ("贡献 2", "记忆系统同时覆盖冷启动领域先验和运行时任务经验。", "automatic experience accumulation"), ("贡献 3", "数学优化实验说明机制不只适用于端到端 MLE。", "cross-domain generalization")]),
 ("整体架构", "每轮包含计划、编码与审查、执行、结果更新；图边区分生成关系和参考关系。", [("三大组件", "Progressive MCGS 控制探索，Retrospective Memory 提供经验，分层规划控制代码改动粒度。", "Progressive Monte-Carlo Graph Search"), ("参考边", "跨分支引用只传递信息，不参与主路径回传，避免把借鉴误算成父子生成。", "Cross-Branch Reference"), ("停滞触发", "分支停滞促成进化或跨分支引用，全局停滞促成多分支聚合。", "global stagnation")]),
 ("问题形式化与图空间", "目标是在结构化候选解空间中最大化任务评价 h(T,s)，并用有向图组织搜索。", [("优化目标", "每个节点代表覆盖预处理、特征工程、训练和预测的完整方案，而不是单个超参数。", "s* = arg max"), ("两类边", "ET 保留父子生成和信用回传；Eref 记录额外参考来源，允许组合非相邻经验。", "Eref = ET union Eref"), ("标准基线", "当没有参考边时，方法退化为标准 MCTS，便于做公平对照。", "standard MCTS")]),
 ("Progressive MCGS：选择与扩展", "方法在 UCT 选择基础上引入随时间衰减的探索权重，并定义四种图扩展操作。", [("探索到利用", "早期用较高熵的 UCT 广泛探索，后期以精英节点为中心集中计算。", "w(t) gradually decreases"), ("四种扩展", "基础扩展、分支内进化、跨分支引用、多分支聚合分别对应由局部到全局的经验复用。", "four expansion types"), ("奖励设计", "执行失败为 -1，成功但未刷新分支最优为 1，刷新最优为 2，明确区分可行性和改进。", "execution fails or no valid metric")]),
 ("回传与停滞检测", "引用信息参与生成但不参与回传，信用只沿主边累积；停滞阈值负责启动更强的重组操作。", [("信用边界", "只沿 ET 更新访问次数和累计奖励，避免参考节点被错误分摊 credit。", "Reference edges are excluded"), ("分支停滞", "连续若干次没有刷新分支最优时，先回看本分支历史，再吸收其他分支强解。", "branch-level stagnation"), ("全局停滞", "全局最优长期不变时从根节点聚合多条轨迹，开辟新的搜索起点。", "multi-branch aggregation")]),
 ("回溯记忆", "Retrospective Memory 把领域知识和运行经验放入每次规划之前的检索环路。", [("冷启动知识", "按任务类型提供模型与用法先验，降低第一批草稿的盲目性。", "cold-start initialization"), ("动态记忆", "每次有效执行记录 plan、outcome、analysis 和 feedback，形成任务内经验库。", "dynamic global memory"), ("检索融合", "BM25 词法检索与 FAISS 向量检索通过 RRF 合并，兼顾精确关键词和语义相似。", "Reciprocal Rank Fusion")]),
 ("规划与自适应编码", "作者把为什么改、改什么与如何实现拆开，再依据搜索状态选择代码生成粒度。", [("Planner-Coder", "Planner 负责模块级策略和约束，Coder 负责在保留可用结构的前提下落地。", "Planner operates at the module level"), ("三种模式", "Base 适合初始完整生成，Stepwise 适合复杂流水线，Diff 适合已有解的局部修补。", "Base mode"), ("实验入口", "第 4 节开始检验这套机制是否真的提高搜索质量、速度和跨域能力。", "Experiments")]),
 ("实验设置与主结果", "MLEvolve 在 75 个 Kaggle MLE-Bench 任务和 15 个数学优化任务上评估。", [("资源约束", "统一使用 12 小时、500 次扩展、21 vCPU、234GB RAM 和单张 H200，低于标准 24 小时预算。", "maximum of 500 expansion steps"), ("MLE-Bench", "低、中、高复杂度奖牌率分别为 80.3%、64.0%、46.7%，总体为 65.3%。", "65.3%"), ("可靠性", "有效提交率 100%，超过人类中位数的任务占 76.0%，金牌率 34.7%。", "100% valid submission rate")]),
 ("数学优化与消融", "跨域任务中 MLEvolve 在 15 个数学优化问题里 11 个取得最佳结果，组件消融则验证三模块互补。", [("跨域结果", "它不是把 MLE 特征硬搬到数学题，而是复用提出-评估-改进的搜索闭环。", "best result on 11 of 15 tasks"), ("组件消融", "移除 Progressive MCGS 或记忆后奖牌率均从 81.82% 降到 68.18%，移除自适应编码降到 72.73%。", "w/o Progressive MCGS"), ("解释", "搜索结构对整体收益影响最大，但三组件缺一都会削弱长程迭代。", "all three components")]),
 ("熵动态与多模型", "实验观察到有效分支数从 4.8 降到 2.8，支持方法从探索转向利用的设计。", [("可观测机制", "MLEvolve 的分支熵随时间下降，而 Vanilla MCTS 始终约 4.3，说明调度并非只停留在公式。", "Effective # of Active Branches"), ("模型无关性", "Gemini、GPT、DeepSeek、Kimi 各自擅长不同领域，但都能在同一框架下取得竞争力。", "not tightly coupled to a specific LLM")]),
 ("长时程曲线与结论", "MLEvolve 在中后期仍持续提升，代表自进化机制主要价值是延长有效改进窗口。", [("速度与上限", "代表任务上最终 Beat Ratio 达 98.2%，Vanilla MCTS 约 70% 后早早停滞。", "98.2%"), ("论文结论", "Progressive MCGS、记忆和分层编码共同支撑 65.3% MLE-Bench 奖牌率。", "sustained experience accumulation"), ("未来方向", "作者计划扩展到自动科学实验、跨学科算法发现和自主研究工作流。", "autonomous research workflows")]),
 ("参考文献", "本页列出 AI for Science、MLE Agent、MCTS、记忆机制和 AlphaEvolve 等研究脉络。", [("阅读重点", "重点追踪 [6] AlphaEvolve、[14] ML-Master、[18] MARS、[24] MLE-Bench，可帮助理解比较对象。", "Alphaevolve"), ("定位", "参考文献页不是新方法证据，应与正文引用位置配合阅读。", "MLE-bench")]),
 ("附录：Agent 角色", "附录把框架拆成 Draft、Improve、Debug、Evolution、Fusion、Aggregation、Review、Leakage、Parse 九类角色。", [("角色分工", "执行错误由 Debug Agent 处理，分支历史由 Evolution Agent 处理，全局停滞由 Aggregation Agent 处理。", "Debug Agent"), ("质量闸门", "Code Review 检查导入、命名和指标一致性，Data Leakage Agent 防止评估泄漏。", "Data Leakage Agent")]),
 ("附录：四种扩展公式", "四种扩展共享 v_new = g_o(v_t,R)，差别在参考集合 R 如何构造。", [("主边不变", "无论采用何种参考，父节点到新节点的 ET 都保留生成顺序。", "v_new = g_o"), ("三种参考", "历史参考用于分支内反思，跨分支参考复用强解，多分支聚合从根创建新轨迹。", "Ragg")]),
 ("附录：MLE-Bench", "MLE-Bench 包含 75 个真实 Kaggle 任务，覆盖视觉、NLP、信号和表格分析，并提供人类基线。", [("任务结构", "22 个低复杂度、38 个中复杂度、15 个高复杂度任务，评价兼顾奖牌、有效提交和超越人类中位数。", "75 carefully curated Kaggle competitions"), ("评价含义", "奖牌不是单一准确率，而是相对 Kaggle 人类参与者的分层门槛。", "Medal Rate")]),
 ("附录：指标与超参数", "作者固定了搜索预算、并行分支数、UCT 衰减和记忆检索阈值，增强跨任务可比性。", [("预算", "每任务最多 500 步、12 小时、3 条并行分支，温度为 1.0。", "time_limit"), ("关键调度", "探索权重在 0.5 到 0.7 的搜索进程区间切换，最低保留 0.2 的探索概率。", "min_exploration_weight"), ("记忆阈值", "向量记忆相似度阈值为 0.7，使用 BGE-base-en-v1.5。", "memory_similarity_threshold")]),
 ("附录：细粒度消融", "去掉分支内进化后 9 任务奖牌率从 66.67% 降到 33.33%，是 Progressive MCGS 内最关键机制。", [("经验复用价值", "分支内进化能避免反复尝试相同失败方向，说明局部轨迹记忆比单次最优更重要。", "w/o Evolution"), ("记忆来源", "知识库帮助冷启动，Global Memory 对长程任务更强，去掉任一者奖牌率都降到 44.44%。", "Global Memory")]),
 ("附录：不同 LLM 与案例", "四种 backbone 在图像、NLP、音频任务上各有强项，案例展示三种图扩展如何落到真实代码修改。", [("模型差异", "没有单一模型统治所有领域，框架提供的是搜索与记忆外壳。", "no single model dominating"), ("案例类型", "第 20-23 页分别展示架构融合、损失替换和多分支组件组合。", "Case Study")]),
 ("案例：分支内进化", "在眼底检测任务中，六次正则化尝试停滞后，Evolution Agent 判断瓶颈来自架构而非优化噪声。", [("诊断", "DINOv3 的全局表示对微小病灶不足，因而引入 ResNet50 的局部归纳偏置。", "architectural inductive bias"), ("实现", "Coder 用 Diff 模式加入 CNN 分支并调整融合头，体现为什么要把策略与实现分离。", "Hybrid ViT-CNN")]),
 ("案例：跨分支引用", "在鸟类音频任务上，当前分支的对称 Focal Loss 停滞，Fusion Agent 从强分支借来 Asymmetric Loss。", [("问题", "极端多标签稀疏下，容易负例数量会淹没稀有正例信号。", "extreme multi-label sparsity"), ("迁移", "只替换损失和训练入口，同时保留随机种子、数据划分和核心架构，降低改动风险。", "Asymmetric Loss")]),
 ("案例：多分支聚合", "全局停滞后，Aggregation Agent 从多个分支组合 EfficientNet-B1、GeM、频带滤波、Focal Loss 和五折交叉验证。", [("组合而非复制", "聚合不是选择一个冠军分支，而是把互补组件拼成新的根分支。", "synthesizes successful components"), ("可复现性提醒", "案例展示的是设计轨迹和代码片段，不等同于对所有任务都有效的固定配方。", "5-Fold Cross-Validation")]),
]

def main():
    for index, (role, summary, points) in enumerate(PAGES, 1):
        data = {"page_summary": summary, "page_role": role, "key_points": [{"title": t, "note": n, "quote": q} for t, n, q in points], "connections": "本页内容服务于论文从搜索机制到实验验证的主线。", "glossary": []}
        (ANALYSIS / f"page_{index:03d}.json").write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    report = {"title_zh": "MLEvolve：自动机器学习算法发现的自进化框架", "one_sentence": "MLEvolve 用图搜索、回溯记忆和分层代码生成，让 LLM Agent 在有限预算下持续改进机器学习方案。", "problem": "现有 MLE Agent 的搜索分支互相隔离、缺少经验积累，并把规划与整段代码生成耦合在一起，长时程优化容易浪费预算、重复失败或失控修改。", "method": "以候选完整 ML 方案为节点构建图。Progressive MCGS 沿主边做 UCT 选择和信用回传，并通过参考边实现分支内进化、跨分支引用和多分支聚合；Retrospective Memory 用领域知识库冷启动，再用 BM25 与 FAISS-RRF 检索运行时经验；Planner 先决定为什么改、改什么，Coder 再在 Base、Stepwise、Diff 三种模式中选择实现粒度。", "innovations": ["用动态参考边实现跨分支信息流，但将其与主路径信用回传分离。", "用熵启发的软切换从早期广泛探索逐渐转向后期精英利用。", "把静态领域先验和动态任务经验统一到规划前检索。", "按搜索状态自适应选择完整重写、分步编码或差分修改。"], "experiments": ["MLE-Bench 75 任务、12 小时预算：平均奖牌率 65.3%，低/中/高复杂度为 80.3%/64.0%/46.7%。", "有效提交率 100%，超过人类中位数 76.0%，金牌率 34.7%。", "AlphaEvolve 数学优化 15 题中 11 题取得最佳结果。", "MLE-Bench Lite 消融：去掉 Progressive MCGS、Retrospective Memory、自适应编码后奖牌率分别降至 68.18%、68.18%、72.73%。", "有效分支数从 4.8 降至 2.8，代表任务最终 Beat Ratio 98.2%，Vanilla MCTS 约 70% 后停滞。"], "limitations": ["论文主要验证 75 个 MLE-Bench 任务和 15 个数学优化任务，跨到真实科学发现的证据仍有限。", "12 小时实验需要 H200、234GB RAM 和多 vCPU，复现实验成本较高。", "主结果采用 Gemini-3.1-Pro-preview，尽管附录测试了其他 backbone，但不同模型的成本和稳定性未充分展开。", "部分案例是设计轨迹展示，不能直接视为对所有任务的通用最优配方。"], "reading_guide": ["先读第 1-4 页掌握三类瓶颈和整体架构。", "再读第 5-9 页，重点理解参考边、熵调度、记忆检索和三种编码模式。", "用第 10-13 页核对主结果、消融和时间曲线。", "最后读第 16-23 页的角色定义、超参数和三个案例。"], "conclusion": "这篇论文最有价值的不是某个单独的 Agent 提示词，而是把长程算法发现视为一个带经验复用和阶段控制的搜索系统。证据支持三组件互补，尤其是分支内历史复用对避免重复失败很关键；但高算力预算、基准覆盖范围和案例外推性仍是实际落地时需要警惕的地方。", "keywords": ["MLEvolve", "Progressive MCGS", "Retrospective Memory", "LLM Agent", "AutoML", "algorithm discovery", "long-horizon optimization"]}
    (ANALYSIS / "report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

if __name__ == "__main__":
    main()
